# Generated by Django 5.1.6 on 2025-03-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='job_Title',
            field=models.TextField(default='unknown'),
        ),
    ]
